version: "3.9"
services:
  pico-w:
    image: php:8.1-apache
    build:
      context: .
    restart: 'no'
    ports:
      - "8086:8086"
    volumes:
      - ./projects:/home/projects
      - ./projects/server:/home/projects/server
      - ./pico-sdk:/home/pico-sdk
    environment:
      PICO_SDK_PATH: /home/pico-sdk
    networks:
      - pico-w 
networks:
  pico-w: